site_name: TiBi
repo_url: https://github.com/rodinalex/TiBi
site_url: https://rodinalex.github.io/TiBi/

theme:
  name: material
  palette:
    scheme: slate
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.instant
    - search.highlight
    - content.code.copy

nav:
  - Home: index.md
  - User Guide: 
      - Installation: user_guide/install.md
      - Getting Started: user_guide/getting_started.md
      - Band structure and DOS: user_guide/bands.md
  - Developer Guide:
      - Architecture: dev/architecture.md
      - Controllers: dev/controllers.md
      - Core: dev/core.md
      - Logic: dev/logic.md
      - Models: dev/models.md
      - UI: dev/ui.md
      - Views: dev/views.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: ["."]
          options:
            docstring_style: numpy
            show_root_heading: true
  - autorefs

markdown_extensions:
  - toc:
      permalink: true
      baselevel: 2
  - admonition
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tabbed
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tilde
  - pymdownx.caret
  - pymdownx.arithmatex:
      generic: true
  - attr_list
  - md_in_html

extra_javascript:
  # - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js